### ISSUE TITLE
Custom fields handling causing unexpected behaviour with devise

### ISSUE THREAD

**Issue by peterox** [shadabahmed/logstasher#114]
Adding a Devise users details as a custom field was causing devise to be initialised prior to the controller action being executed. This is due to the fact that the custom fields were being added before the controller action.

Also, custom fields are not being added if an exception was thrown from the controller.

**Comment by johnowenatala** [comment]
Hi, 

checking code, I think problem is here:

`LogStasher.custom_fields += after_keys - before_keys`
https://github.com/shadabahmed/logstasher/blob/master/lib/logstasher/rails_ext/action_controller/metal/instrumentation.rb#L31

This other file has the same, but now changed to this:
`LogStasher::CustomFields.add(*(after_keys - before_keys))`
https://github.com/shadabahmed/logstasher/blob/master/lib/logstasher/rails_ext/action_controller/base.rb#L27

By the way, please check this two classes - they seem very similar and looks like they are trying to do the same method override with very little differences, which doesnt look right - and looks like it can be broken very easy.

**Comment by MarcGrimme** [comment]
You are right. I overlooked this line.
```
LogStasher.custom_fields += after_keys - before_keys
``` 
in [lib/logstasher/rails_ext/action_controller/metal/instrumentation.rb](https://github.com/shadabahmed/logstasher/blob/master/lib/logstasher/rails_ext/action_controller/metal/instrumentation.rb#L31). So it needs to be fixed.

FYI: Both classes are indeed similar should deliver the SAME functionality. I introduced them to offer two ways of using logstasher [one with implicit monkey patching](https://github.com/shadabahmed/logstasher/blob/master/lib/logstasher/rails_ext/action_controller/metal/instrumentation.rb) and [one by explicit documented including](https://github.com/shadabahmed/logstasher/blob/master/lib/logstasher/rails_ext/action_controller/base.rb).

**Comment by shadabahmed** [comment]
Cloding this as fixed in #115
