### ISSUE TITLE
Parameters are not logged 

### ISSUE THREAD

**Issue by notpad** [shadabahmed/logstasher#116]
When I set log_controller_parameters to true, the parameters are still not included in the log.

I took a look on the code, and found that this line is added to https://github.com/shadabahmed/logstasher/blob/master/lib/logstasher/rails_ext/action_controller/metal/instrumentation.rb in commit https://github.com/shadabahmed/logstasher/commit/98bf68c9033419e8ff09790630d44481f05492fd which I think is not necessary:

`LogStasher::CustomFields.clear`

Because it will clear all the custom fields before they are logged.

**Comment by MarcGrimme** [comment]
I would state it like this.
The call is necessary but needs to be one line above.
The ``LogStasher.add_default_fields_to_payload(raw_payload, request)`` fills in the ip and stuff to the global cache and is then cleared. That's wrong.
I didn't see it cuz I'm using the [logstasher/rails_ext/action_controller/base.rb](https://github.com/shadabahmed/logstasher/blob/master/lib/logstasher/rails_ext/action_controller/base.rb#L4-L11) and this is not affected. I'll issue a PR.

**Comment by MarcGrimme** [comment]
Could you perhaps check if it's fine now. I'd merge it if you say it's working now.

**Comment by notpad** [comment]
I am afraid that this won't work, because LogStasher::CustomFields.clear is still there.

**Comment by MarcGrimme** [comment]
Should be fixed with #119 . Closing this one.
