### ISSUE TITLE
Adding custom fields to the log is not working with rails 3.2.13

### ISSUE THREAD

**Issue by sumanranjanpanda** [shadabahmed/logstasher#2]
Adding custom fields to the log is not working with rails 3.2.13 and logstasher 0.2.5.
I have followed all the step and created a file as **config/initializers/logstasher.rb**. Following are the code inside the file "logstasher.rb"

```
if LogStasher.enabled
 LogStasher.add_custom_fields do |fields|
    fields[:country_code] = "US"
 end
end
```

After that I have restarted the webrick server, but the **LogStasher.enaabled** returns nil value and not storing the country code in the log file.

My requirement is like, I need to save the location information to the log file with the other information to display the kibana map.

Can you plz help me?

**Comment by mdarby** [comment]
Sorry to resurrect a closed issue but I'm seeing exactly the same thing and moving the gem/initializer up the load order doesn't seem to work. Getting logs, parsing just fine but no custom fields even when the normal wrapping `if` is removed.

**Comment by mdarby** [comment]
```
LogStasher.add_custom_fields do |fields|
  ip = request.env['HTTP_X_FORWARDED_FOR'] || request.remote_ip

  puts "-" * 10
  puts ip
  puts "-" * 10

  fields[:ipaddr] = ip
end
```

This produces the IP in the logs but no custom field.
