### ISSUE TITLE
Formatting ALL logs as JSON for logstash?

### ISSUE THREAD

**Issue by krancour** [shadabahmed/logstasher#25]
Great gem!  Thank you for this.

I am noting something, however, that's counter-intuitive.  It seems this only replaces Rails' default _request_ logging, but not _all_ logging across the board.  For instance, arbitrary log messages like `log.debug 'Hello, World!'` don't get formatted as JSON and still go to the usual <environment>.rb log file.

The documentation also alludes to this limitation in a list of project goals:

> Prevent any logger messages(e.g. info) getting into our pure json logs

I am thinking, however, that there are probably many folks like myself that would like _all_ application logs to go to the same place.  In many cases, the sort of log messages that logstasher is _not_ currently bothering with might be much more valuable than the request logs- which are often dialed down in production anyway to reduce noise.

What would be your thoughts on updating the gem to at least offer the option of replacing Rails.logger with a LogStasher?  (Note I have tried this already and it does not work at present.)

I'd be happy to help out with this a little, but have to admit I'm a pretty new to the internals of Rails' logging- which is why I am raising this as a question/comment first instead of jumping straight to a pull request.

**Comment by retgoat** [comment]
@krancour  If I understand you correctly, you'd like to push ALL your application logs into logstash.
After some googling I've found the way to manage it: https://github.com/dwbutler/logstash-logger

For application logs:

```ruby
# config/environments/development.rb (or config/application.rb)
require 'logstash-logger'
Rails.logger = LogStashLogger.new([{type: :file, path: 'log/development.log'}, {type: :udp, host: 'localhost', port: 5923}])
```

For sidekiq logs:
```ruby
Sidekiq::Logging.logger = LogStashLogger.new([{type: :file, path: 'log/sidekiq.log'}, {type: :udp, host: 'localhost', port: 5923}])
```

Here is the logstash output:
```
{
       "message" => "Connecting to database specified by database.yml",
    "@timestamp" => "2015-03-10T13:13:41.833+07:00",
      "@version" => "1",
      "severity" => "INFO",
          "host" => "ubuntu"
}
{
       "message" => " 2015-03-10 13:13:49 INFO tagged_logging.rb:5:in `block in tagged' -- \n",
      "@version" => "1",
    "@timestamp" => "2015-03-10T06:13:49.355Z",
          "host" => "127.0.0.1"
}
{
       "message" => " 2015-03-10 13:13:49 INFO tagged_logging.rb:5:in `block in tagged' -- \n",
      "@version" => "1",
    "@timestamp" => "2015-03-10T06:13:49.356Z",
          "host" => "127.0.0.1"
}
{
       "message" => "Started 2015-03-10 13:13:49 INFO tagged_logging.rb:5:in `block in tagged' -- POST \"/psp/entrypoint\" for 192.168.56.1 at 2015-03-10 13:13:49 +0700\n",
      "@version" => "1",
    "@timestamp" => "2015-03-10T06:13:49.356Z",
          "host" => "127.0.0.1"
}
{
       "message" => "Processing 2015-03-10 13:13:50 INFO log_subscriber.rb:93:in `call' -- by PspController#entrypoint as JSON\n",
      "@version" => "1",
    "@timestamp" => "2015-03-10T06:13:50.568Z",
          "host" => "127.0.0.1"
}
{
       "message" => "Parameters: 2015-03-10 13:13:50 INFO log_subscriber.rb:93:in `call' -- {\"json\"=>\"[FILTERED]\"}\n",
      "@version" => "1",
    "@timestamp" => "2015-03-10T06:13:50.569Z",
          "host" => "127.0.0.1"
}
{
       "message" => "PSP: 2015-03-10 13:13:50 INFO base.rb:167:in `process_action' -- Ukash, action: get_deposit_form_fields\n",
      "@version" => "1",
    "@timestamp" => "2015-03-10T06:13:50.596Z",
          "host" => "127.0.0.1"
}
{
       "message" => "Response: 2015-03-10 13:13:50 INFO base.rb:167:in `process_action' -- \"response here \n",
      "@version" => "1",
    "@timestamp" => "2015-03-10T06:13:50.689Z",
          "host" => "127.0.0.1"
}
```

Hope it helps.

**Comment by Mehonoshin** [comment]
Hi folks!
Very interesting discussion.

@krancour, what's about your research? can you share some sources?

**Comment by MarcGrimme** [comment]
@retgoat your approach does not really fix the problem. The logstash-logger does not overwrite/monkeypatch the ``<<`` method as described before and therefore the logs added directly are not formated and plain text again.

For example when you execute your code and do the following
``
Rails.logger << "test123"
``
it's not properly formated.

This holds for example for the SQL logs.

At least IMHO.

**Comment by retgoat** [comment]
@MarcGrimme you're absolutely right. If you'll call logger as ```Rails.logger << "test123"``` you'll get just plain text string. This is normal because you call logger w/o severity and formatter.
Here is what I've got:

```ruby
Rails.logger << "test123"
```

```json
{
  "message":"Lang: text_tr: Tutar","
  @timestamp":"2015-03-27T18:28:53.813+07:00",
  "@version":"1",
  "severity":"INFO",
  "host":"ubuntu",
  "@caller":"logger.rb:434:in `info'"
}
{
  "message":"Lang: text_tr: Processing time: 1 hour",
  "@timestamp":"2015-03-27T18:29:13.071+07:00",
  "@version":"1",
  "severity":"INFO",
  "host":"ubuntu",
  "@caller":"logger.rb:434:in `info'"
}

test123
```

Approach suggested by me proceeds from assumption that you always call logger with as `
```ruby
Rails.logger.SEVERITY "Message"
```

In that way you'll always get that you want.

```ruby
Rails.logger.info "text123"
```

```json
{
  "message":"test123",
  "@timestamp":"2015-03-30T09:23:01.754+07:00",
  "@version":"1",
  "severity":"INFO",
  "host":"ubuntu",
  "@caller":"logger.rb:434:in `info'"
}
```

Btw, to avoid situations when log messages can't be accepted by logstash and keep all the log messages from your app you could just use broadcast method: http://stackoverflow.com/questions/6407141/how-can-i-have-ruby-logger-log-output-to-stdout-as-well-as-file/29006762#29006762

All above is IMHO ofc.

**Comment by ibrahima** [comment]
Did anyone here actually end up figuring out how to use Logstasher for Sidekiq logs? I saw this gist from Sam Saffron but I can't figure out if it's still usable or how to actually use it. https://gist.github.com/SamSaffron/6876657

**Comment by retgoat** [comment]
@ibrahima 
I tried to wrap all the thing up in that gist https://gist.github.com/retgoat/c9023b81c53ddff2f3dc

**Comment by ibrahima** [comment]
Ah, thanks! I ended up using Sidekiq-Logging-JSON instead of LogstashLogger.
