### ISSUE TITLE
Customizing log file name and path?

### ISSUE THREAD

**Issue by san** [shadabahmed/logstasher#28]
Just seeking comments here. Would it be a good idea to allow customizing log filename and path via app.config option like this below?

```
# If you want logstasher to log to a different file, uncomment and modify the line below.
# Defaults to "#{Rails.root}/log/logstash_#{Rails.env}.log"
config.logstasher.log_file = "/path/to/log/file/filename.log"
```

In my use case, I am sort of needing to do that.

Comments appreciated.

Thanks.

**Comment by agrass** [comment]
+1
