### ISSUE TITLE
Could not log "process_action.action_controller" event

### ISSUE THREAD

**Issue by anlek** [shadabahmed/logstasher#45]
On Exceptions I get the following error:
`Could not log "process_action.action_controller" event. NoMethodError: undefined method`<<' for nil:NilClass`coming from`logstasher-0.2.8/lib/logstasher/log_subscriber.rb:17`
I'm using rails 4.1.4.

**Comment by ishaansutaria** [comment]
I am still getting into this issue

**Comment by ishaansutaria** [comment]
Could not log "process_action.action_controller" event. NoMethodError: undefined method `first' for nil:NilClass
