### ISSUE TITLE
Exclude some params from "Logging params hash"

### ISSUE THREAD

**Issue by davetoxa** [shadabahmed/logstasher#66]
I realized, that i have no need to send some fields, such as `utf8, authenticity_token, password`

Need some settings to do this, that do you think about it?

**Comment by pledgemusic** [comment]
disable config.logstasher.log_controller_parameters option, then do something like:

`
if LogStasher.enabled
  LogStasher.add_custom_fields do |fields|
    fields[:params] = request.filtered_parameters.except(:utf8)
  end
end
`

in your initializer

(except might not be right method to use but however you want to filter that hash down would work)
