### ISSUE TITLE
How can I forward this to stdout?

### ISSUE THREAD

**Issue by dannylui** [shadabahmed/logstasher#68]
I'm trying to use this gem inside a docker container, and docker logs work best with stdout.  I tried configuring `config.logstasher.logger_path` to /dev/stdout, but I would get the following error:  

`Message from application: No such device or address @ rb_sysopen - /dev/stdout (Errno::ENXIO)`

**Comment by dannylui** [comment]
I managed to send the log to stdout by making the following change in lib/logstasher.rb:

```
  def new_logger(path)
    if path.is_a? String
      FileUtils.touch path # prevent autocreate messages in log
    end
    Logger.new path
  end
```

**Comment by alext** [comment]
Alternatively, instead of setting `logger_path` you can set `logger` directly:
```ruby
config.logstasher.logger = Logger.new(STDOUT)
```
