### ISSUE TITLE
Logstasher is not Logging Errors

### ISSUE THREAD

**Issue by msdundar** [shadabahmed/logstasher#79]
Hi,

I'm running a rails 4 application in development mode.

Here is my `config/environments/development.rb` =>

```
  # Logstasher Config
  # Enable the logstasher logs for the current environment
  config.logstasher.enabled = true

  # This line is optional if you do not want to suppress app logs in your <environment>.log
  config.logstasher.suppress_app_log = false

  # This line is optional, it allows you to set a custom value for the @source field of the log event
  config.logstasher.source = 'foobar'

  # This line is optional if you do not want to log the backtrace of exceptions
  config.logstasher.backtrace = false

  # This line is optional, defaults to log/logstasher_<environment>.log
  config.logstasher.logger_path = 'log/logstasher.log'
```

The problem is, when an application error occurs (like 404 not found) I can see the error in `log/development.log` but not in `log/logstasher.log`

How can I solve this issue?

**Comment by sfate** [comment]
Seems problem occurs for any log_level..
As you can see here: https://github.com/shadabahmed/logstasher/blob/master/lib/logstasher/railtie.rb#L7
Logstasher initialized as instance of `ActiveSupport::OrderedOptions`: 
```ruby
config.logstasher = ActiveSupport::OrderedOptions.new
```
But in new rails it also inherit an `ActiveSupport` default logger, which sending output to stdout. 

And after that.. we moving to `setup` method.. where we have already defined logger:
```ruby
self.logger = app.config.logstasher.logger || new_logger(self.logger_path)
```
And now at any call of `logger` output sends to default `ActiveSupport::OrderedOptions` logger..

This can be monkeypatched as follow:
```ruby
# add this info your development.rb or other environment file
config.to_prepare do
  LogStasher.logger = Logger.new("#{Rails.root}/log/logstash_#{Rails.env}.log")
end
```

**Comment by hut8** [comment]
+1 for this issue -- even with the monkey patch, I can't get my development `Rails.logger.info` to display anything in the logstash log.

**Comment by astutejoe** [comment]
Same here... Even with the ninja Monkey Patch, no logger calls is logged

**Comment by MarcGrimme** [comment]
You might want to check #108 .
There is still the TODOs:
* Add tests
* Check for production env (or any other) not so sure if it works there
But this could be a solution.
Comments welcome.

**Comment by MarcGrimme** [comment]
Other then this I'd say get it merged soon as this is really a pain.
